# Copygright 2016 Google Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to writing, software distributed
# under the License is distributed on a "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static

env_variables:
  API_KEY: 'get your own!'

# Sign up to openweathermap.org and obtain a new API key, then replace the value of API_KEY.
